### ISSUE TITLE
Null is not an object error

### ISSUE THREAD

**Issue by JackGlobetrotter** [andreshsingh/bcrypt-react-native#4]
Trying to use the npm package via npm install in an expo application (running on IOS14)
running any methode from the package gives me the following error: 
``````````````````
  "e": [TypeError: null is not an object (evaluating 'BcryptReactNative.default.getSalt')
``````````````````

I am grateful for any ideas?

**Comment by andreshsingh** [comment]
Hey @JackGlobetrotter, this package contains native code hence is only for projects created with react native cli and expo ejected
