### ISSUE TITLE
.hash Parameter order

### ISSUE THREAD

**Issue by AlphaJuliettOmega** [andreshsingh/bcrypt-react-native#6]
This library's first example has the Hash function with parameters the opposite way round to other implementations:
This library:
```const hash = await BcryptReactNative.hash(salt, 'password');```

vs 

```var hash = bcrypt.hashSync("B4c0/\/", salt);```
https://www.npmjs.com/package/react-native-bcrypt

and: 
```const salt = bcrypt.genSaltSync(saltRounds);
const hash = bcrypt.hashSync(myPlaintextPassword, salt);```
https://github.com/kelektiv/node.bcrypt.js

Is this intended?

I've been struggling to get a comparison to succeed with the sync function as was wondering if there's a simple parameter swap going on.

**Comment by andreshsingh** [comment]
<img width="833" alt="Screen Shot 2021-04-05 at 4 51 29 PM" src="https://user-images.githubusercontent.com/30138390/113567901-37479700-962f-11eb-9a6c-67a1a419e5d9.png">

![Screen Shot 2021-04-05 at 4 51 36 PM](https://user-images.githubusercontent.com/30138390/113567996-665e0880-962f-11eb-93d5-aaa3931993ec.png)

@AlphaJuliettOmega  can you please check? it is working fine for me...The order is as it is described in the docs

**Comment by AlphaJuliettOmega** [comment]
@andreshsingh thank you for taking the time to look into it, it's working as expected after more testing and making sure my async operations are correct - the issue was in another area of the application :)
