### ISSUE TITLE
Running cd pod install produces error on Mac

### ISSUE THREAD

**Issue by proffnick** [andreshsingh/bcrypt-react-native#9]
Please how do I solve this ?

[!] CocoaPods could not find compatible versions for pod "bcrypt-react-native":
  In Podfile:
    bcrypt-react-native (from `../node_modules/bcrypt-react-native`)

Specs satisfying the `bcrypt-react-native (from `../node_modules/bcrypt-react-native`)` dependency were found, but they required a higher minimum deployment target.

**Comment by andreshsingh** [comment]
In podfile change to platform :ios, '11.0'

**Comment by hainguyentien** [comment]
![image](https://user-images.githubusercontent.com/36818841/123540861-4a1fc280-d76b-11eb-8db3-23f6f87013ac.png)
@andreshsingh  This is what happened when i change Podfile to platform :ios, '11.0', any solution here, please?

**Comment by andreshsingh** [comment]
well the error is not detailed enough...could you please try to clean build folder and run in simulator in debug mode instead of release mode ? let me know if that helps @hainguyentien

**Comment by hainguyentien** [comment]
> well the error is not detailed enough...could you please try to clean build folder and run in simulator in debug mode instead of release mode ? let me know if that helps @hainguyentien

I currently using iPhone 12 mini for debug build, ios 14.5, and I also clean build folder for several times. But it's not work
